### ISSUE TITLE
Warning: This feature is not supported on camera without autofocus

### ISSUE THREAD

**Issue by YudizAndroidHardik** [microblink/blinkid-android#293]
### Description

I am following your repo and running the code of **BlinkId-ImagesSample**.

When I click on Scan Document, it shows a warning as mentioned above.

As a Recogniser, I am using BlinkIdSingleSideRecognizer. when I call requiresAutofocus(), it will return true. means this is a mandatory thing

So Is there any way to prevent this issue? 

### Environment Details

**BlinkID version: V6.1.1**

**Device model: Samsung Galaxy Tab A**

**Device Android version: 9**

**Device ABI (processor architecture, e.g. ARMv7):**

**Comment by Brankacro** [comment]
Hello @YudizAndroidHardik. 
You can only check if the end user has a device with autofocus. If the camera is without the autofocus, you will get the described alert.
Having a device that has a camera with autofocus is one of our requirements.
Please let us know if we can be of any additional help.
Best.

**Comment by YudizAndroidHardik** [comment]
Thank you for your response

Can we do it without autofocus?

**Comment by Brankacro** [comment]
Hello @YudizAndroidHardik. A camera with autofocus is required.
If there is anything else that we can assist you with, please let us know. Best.

**Comment by Brankacro** [comment]
Hello @YudizAndroidHardik.
The only alternative that we can suggest is direct API. More precisely, that the end user directly uploads the image from the gallery to the SDK for processing.

More you can find on this [link](https://github.com/BlinkID/blinkid-android#direct-api) and here you can find the [link](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID-DirectApiSample) for the sample.

Hope this info helps.
Please let us know in case of any additional questions.

**Comment by Brankacro** [comment]
Hello @YudizAndroidHardik. Since this topic is inactive, we'll be closing it. If anything comes up feel free to reach out. You can also contact us at support@microblink.com. We'll be glad to hear from you. Best.

**Comment by albert0m** [comment]
Hi, I'm commenting this thread because it's kind of related.
I'm trying to test your framework on an android tv with an usb camera attached to it.
Everything works as expected, if I programmatically check for autofocus 

```
if(pm.hasSystemFeature(PackageManager.FEATURE_CAMERA) && pm.hasSystemFeature(PackageManager.FEATURE_CAMERA_AUTOFOCUS)){
            // True 
        }
```

it returns true meaning that the autofocus works (it's a Logitech C930e), if I use the camera app I can see the camera autofocusing. 

The blinkid app crashes though:

 `com.microblink.blinkid.hardware.camera.AutoFocusRequiredButNotSupportedException: Autofocus is required, but not supported on this camera`

what kind of strategies do you check to see if autofocus really works?

**Comment by Brankacro** [comment]
Hello @albert0m and thank you for waiting for our reply.

Setups with external cameras are currently not supported. Our camera management supports only the device's internal cameras.
We can suggest that you use direct API, where the end user directly uploads the image from the gallery to the SDK for processing.
More you can find on this [link](https://github.com/BlinkID/blinkid-android#direct-api) and here you can find the [link](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID-DirectApiSample) for the sample. 

Hope this info was helpful.
For any other questions, feel free to contact us.

**Comment by Brankacro** [comment]
Hello @albert0m. Since this topic is inactive we'll be closing it. In case of any additional questions, please let us know. Also, feel free to reach out to us at support@microblink.com. We'll be glad to assist. Best.
