### ISSUE TITLE
Invalid license buffer magic number.

### ISSUE THREAD

**Issue by mandrachek** [microblink/blinkid-android#304]
We've seen a couple of crash reports come in when setting license keys:

```
com.microblink.blinkid.licence.exception.InvalidLicenceKeyException
Invalid license buffer magic number. License buffer is corrupted!
```

Both crashes are from Android 11, one OnePlus8Pro and one Huawei Enjoy 9s.
Using SDK 6.2.2

Any ideas what could cause this?

**Comment by mandrachek** [comment]
I found a reference to this same exception #163 - I'm sure quite sure that our key is correct.  This appears to only happen occasionally, and so far we have only seen it on Android 11.

**Comment by MBrizic01** [comment]
Hi @mandrachek , thank you for reaching out. This kind of license exception usually indicates that you haven't properly entered the license key string. Usually, there is an additional character, or an additional space is added in the license key string. 

We are supporting Android 11, so this shouldn't be an issue.

If the exception is happening occasionally, it could indicate that the affected devices are rooted. Are you able to check it on your end? Does it happen in a testing or production environment?

**Comment by mandrachek** [comment]
@MBrizic01 - it's in our production release.  According to crashlytics, both devices are rooted.

**Comment by MBrizic01** [comment]
@mandrachek Thank you for checking this. Please reach out to support@microblink.com with the license key number and described behavior. Meanwhile, we will check if we can test it on the reported devices and let you know our findings.

**Comment by MBrizic01** [comment]
@mandrachek We checked this further and cannot guarantee that our SDK will work on such devices. Officially, we do not support devices that are jailbroken/rooted. We expect the original OS to be published by the device manufacturer as we know their standards so we can test our builds to ensure that everything is working correctly.
