### ISSUE TITLE
doesn't read first/last name or doc number from some type of Chinese passport

### ISSUE THREAD

**Issue by hanwoo-kim** [microblink/blinkid-android#305]
Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-faq-and-known-issues)

---

### Description

Tested some Chinese passport images which found from Google search.
BlinkID scans correctly most of them, but we found that it was not successful at some types of Chinese passport.
**It happens on both of Android and iOS.**

Chinese passport 
 - version 1997-2 -> OK
 - **version 2019 -> No first/last name**
 - version 2021 -> OK

Taiwan passport -> OK
**Hongkong passport -> No document number**
Macao passport -> OK

Please find the photos what I collected from the Google photos album link below.
https://photos.app.goo.gl/7X2i58pyJ7ax8wFF6

You'll be able to see the type of passport from the file name.

### Environment Details

**BlinkID version:**
Android: 6.2.2
iOS: 6.2.1

**Device model:**

**Device Android version:**

**Device ABI (processor architecture, e.g. ARMv7):**

### Log file

Please enable logging by following instructions [here](https://github.com/BlinkID/blinkid-android#other-problems) and attach full log file.

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

**Comment by somyaguptagit** [comment]
Hello @hanwoo-kim Thank you for reporting the issue and sharing the details.
We would kindly request you to share the license numbers(starting LIC00...) that you are using in your project, and also contact us at support@microblink.com.

**Comment by woodenh** [comment]
This issue was resolved by using mrzResult object to get name fields and doc number field.
Thanks for the supports!

Please close this case.
