### ISSUE TITLE
DateResult and Date toString returns appended data instead of interleaved

### ISSUE THREAD

**Issue by StanoJakAcc** [microblink/blinkid-android#308]
### Description

After a successful scan, calling the toString() function on DateResult data returns appended data instead of interleaving them.
For example: `Date: %s, original string: %s, isFilledByDomainKnowledge: %s04.09.2014.04 SEPT/SEPT 14false`

This string was retrieved like
`BlinkIdMultiSideRecognizer.getResult().getDateOfIssue().toString()`

Similar results are achieved for calling the toString() function on Date data.
For example for `BlinkIdMultiSideRecognizer.getMrzResult().getDateOfExpiry().toString()`, we get
`Date: %s, original string: %s, isFilledByDomainKnowledge: %s04.09.2024.240904false`

I suspect this is caused by the use of append in the toString function of the Date/DateResult classes
![image](https://github.com/BlinkID/blinkid-android/assets/98980067/57657298-13e2-4dfd-8607-cb2c7fb26232)

### Environment Details

**BlinkID version:** 6.3.0

**Comment by anjapenic** [comment]
hey @StanoJakAcc, if you want to extract the date of issue, you can do it like this:
`BlinkIdMultiSideRecognizer.getResult().getDateOfIssue().getDate().toString()
`
let me know if this helped or if you're expecting a different outcome

**Comment by StanoJakAcc** [comment]
Hi, yes we came to this same conclusion ourselves, this solution you provided works for us, we've adapted our code for it.

Nevertheless, I believe the original issue with toString() is still valid.

**Comment by anjapenic** [comment]
hi @StanoJakAcc, you're absolutely right, thanks for pointing out this bug, we'll make sure to fix it in our next release, v6.4.0. In the meantime, if you'd like to get this string on your end, you can do so like this:

`public String toString() {
        return String.format(Locale.getDefault(), "Date: %s, original string: %s, isFilledByDomainKnowledge: %s", (getDate() == null ? "null" : getDate().toString()), getOriginalDateString(), isFilledByDomainKnowledge());
    }`

**Comment by krizaa** [comment]
Hi, this has been fixed in BlinkID v6.4.0.
Thanks for reporting the bug and if the problem persists, please create a new issue
