### ISSUE TITLE
Sample apps use an outdated version of BlinkID and don't compile with the current version (6.5.0)

### ISSUE THREAD

**Issue by Vlad-M-1** [microblink/blinkid-android#315]
### Description

Sample apps (BlinkIDSample folder in this repository) use BlinkId 5.10.0. The current version (6.5.0) has multiple differences from it. And if I change the BlinkId version to 6.5.0, the examples just don't compile.

Steps to reproduce:
• Clone the repository
• Open BlinkIDSample/build.gradle
• Change blinkIdVersion = '5.10.0' to blinkIdVersion = '6.5.0'
• Try to run the samples. For example, BlinkID-DirectApiSample
• Observe Gradle reporting errors in multiple files. 
In my case, it were 14 files.

**Comment by krizaa** [comment]
Hi @Vlad-M-1, are you on latest master commit? 
Our samples are on latest BlinkID version: https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/build.gradle#L28
