### ISSUE TITLE
Upgrading to Version 6.6.0 but the SDK is not working

### ISSUE THREAD

**Issue by arunprasath218** [microblink/blinkid-android#319]
### Description

My project is currently using Version 6.4.0. I had ANR issues when Activity goes into pause state. I was told that the ANR will be fixed in Version 6.6.0. 

I have upgraded to Version 6.6.0 but its not working. I have tested on multiple devices and when connected on wifi it will return Unable to do remote license check and when device connected to mobile data nothing happens when I am trying to scan the ID. 

I also checked using Blink ID sample app and the sample app also has the same isssues

**Comment by MBrizic01** [comment]
Hi @arunprasath218, thank you for reporting this. We are working on a fix and will let you know once we release it.

**Comment by MBrizic01** [comment]
Hello @arunprasath218, the [release](https://github.com/BlinkID/blinkid-android/releases/tag/v6.6.1) containing the fix is out. Feel free to test it out. I appreciate your patience. :)
