### ISSUE TITLE
Feature Request: Height, Eye Color, Hair Color, Weight Support

### ISSUE THREAD

**Issue by mandrachek** [microblink/blinkid-android#324]
US driver's licenses often include height, eye color, hair color, and in some cases weight. It would be good to be able to get these values where feasible.

**Comment by MBrizic01** [comment]
Hi @mandrachek you can access these values through from BarcodeResult structure where we added [extededElements](https://github.com/BlinkID/blinkid-android/blob/beecadc4a71139d45e908039ec23fc251ae214d4/BlinkIDSample/LibUtils/src/main/java/com/microblink/blinkid/result/extract/blinkid/generic/BlinkIdMultiSideRecognizerResultExtractor.java#L421)  You can find all data from AAMVA-compliant barcodes under their respective `BarcodeElementKey` in the `BarcodeElements` structure. For a full list of keys please see [here](https://github.com/BlinkID/blinkid-ios/blob/ee1f5d18670976e02bb15ee8364ded264ad905f3/BlinkID.xcframework/ios-arm64/BlinkID.framework/Headers/MBUsdlKeys.h#L11).

**Comment by mandrachek** [comment]
@MBrizic01 - Ah, ok, I see.  It wasn't clear looking at the javadocs for the `BlinkIdMultiSideRecognizer.Result` how to access this information.  That sample cleared quite a few things up for me. Giving this is blinkid-android though, I think I should probably be looking at https://blinkid.github.io/blinkid-android/com/microblink/blinkid/entities/recognizers/blinkid/idbarcode/BarcodeElementKey.html rather than the blinkid-ios struct. :). Thanks.
